include: 'https://raw.githubusercontent.com/Nitrokey/common-ci-jobs/master/common_jobs.yml'

stages:
  - pull-github
  - fetch
  - build
  - deploy

variables:
  #Repo for shared scripts (pull.sh release.sh, nightly_upload.sh):
  GIT_STRATEGY: clone     #This seems to have no effect also set in webinterface
  GIT_DEPTH: 0          #This seems to have no effect also set in webinterface
  GIT_SUBMODULE_STRATEGY: recursive #This seems to have no effect also set in webinterfac
  SCRIPTS_REPO: git@git.dotplex.com:nitrokey/gitlab-ci.git
  REPO_USER: nitrokey
  REPO_NAME: libnitrokey
  MAIN_BRANCH: master
  COMMON_PULL: "true"
  COMMON_UPLOAD_NIGHTLY: "true"
  COMMON_GITHUB_RELEASE: "false"
  COMMON_UPLOAD_FILES: "false"

#registry.git.dotplex.com/nitrokey/libnitrokey/libnitrokey-bionic-llvm7   latest            c1975c526258   56 minutes ago   929MB
#registry.git.dotplex.com/nitrokey/libnitrokey/libnitrokey-bionic-gcc8    latest            0c6517c2cdfb   57 minutes ago   628MB
#registry.git.dotplex.com/nitrokey/libnitrokey/libnitrokey-bionic-gcc7    latest            1e90cda7bd9e   58 minutes ago   516MB
#registry.git.dotplex.com/nitrokey/libnitrokey/libnitrokey-bionic-gcc6    latest            3156dc02e022   58 minutes ago   899MB
#registry.git.dotplex.com/nitrokey/libnitrokey/libnitrokey-bionic-gcc5

fetchAndPackage:
  image: registry.git.dotplex.com/nitrokey/libnitrokey/libnitrokey-bionic-gcc8:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - docker
  stage: fetch
  before_script: 
    - apt-get update
    - apt-get -y install git wget
  script: 
    - chmod +x ci-script/package.sh
    - ci-script/package.sh
  after_script:
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - output
      - libnitrokey-source-metadata
    expire_in: 2 weeks

build-bionic-gcc8:
  image: registry.git.dotplex.com/nitrokey/libnitrokey/libnitrokey-bionic-gcc8:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - docker
  stage: build
  before_script: 
    - apt-get update
    - apt-get -y install wget curl
  script: 
    - chmod +x ci-script/build.sh
    - ci-script/build.sh
    - mkdir -p artifacts
    - cp libnitrokey-source/output/*.tar.gz artifacts
  after_script:
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}
  artifacts:
    paths:
      - artifacts
    expire_in: 2 weeks
    