# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/george/Projects/nitrokey/nitrokey-app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/george/Projects/nitrokey/nitrokey-app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/george/Projects/nitrokey/nitrokey-app/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/george/Projects/nitrokey/nitrokey-app/CMakeFiles /home/george/Projects/nitrokey/nitrokey-app/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/george/Projects/nitrokey/nitrokey-app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nitrokey-app

# Build rule for target.
nitrokey-app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nitrokey-app
.PHONY : nitrokey-app

# fast build rule for target.
nitrokey-app/fast:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/build
.PHONY : nitrokey-app/fast

aboutdialog.o: aboutdialog.cpp.o
.PHONY : aboutdialog.o

# target to build an object file
aboutdialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/aboutdialog.cpp.o
.PHONY : aboutdialog.cpp.o

aboutdialog.i: aboutdialog.cpp.i
.PHONY : aboutdialog.i

# target to preprocess a source file
aboutdialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/aboutdialog.cpp.i
.PHONY : aboutdialog.cpp.i

aboutdialog.s: aboutdialog.cpp.s
.PHONY : aboutdialog.s

# target to generate assembly for a file
aboutdialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/aboutdialog.cpp.s
.PHONY : aboutdialog.cpp.s

base32.o: base32.cpp.o
.PHONY : base32.o

# target to build an object file
base32.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/base32.cpp.o
.PHONY : base32.cpp.o

base32.i: base32.cpp.i
.PHONY : base32.i

# target to preprocess a source file
base32.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/base32.cpp.i
.PHONY : base32.cpp.i

base32.s: base32.cpp.s
.PHONY : base32.s

# target to generate assembly for a file
base32.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/base32.cpp.s
.PHONY : base32.cpp.s

command.o: command.cpp.o
.PHONY : command.o

# target to build an object file
command.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/command.cpp.o
.PHONY : command.cpp.o

command.i: command.cpp.i
.PHONY : command.i

# target to preprocess a source file
command.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/command.cpp.i
.PHONY : command.cpp.i

command.s: command.cpp.s
.PHONY : command.s

# target to generate assembly for a file
command.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/command.cpp.s
.PHONY : command.cpp.s

crc32.o: crc32.cpp.o
.PHONY : crc32.o

# target to build an object file
crc32.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/crc32.cpp.o
.PHONY : crc32.cpp.o

crc32.i: crc32.cpp.i
.PHONY : crc32.i

# target to preprocess a source file
crc32.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/crc32.cpp.i
.PHONY : crc32.cpp.i

crc32.s: crc32.cpp.s
.PHONY : crc32.s

# target to generate assembly for a file
crc32.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/crc32.cpp.s
.PHONY : crc32.cpp.s

device.o: device.cpp.o
.PHONY : device.o

# target to build an object file
device.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/device.cpp.o
.PHONY : device.cpp.o

device.i: device.cpp.i
.PHONY : device.i

# target to preprocess a source file
device.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/device.cpp.i
.PHONY : device.cpp.i

device.s: device.cpp.s
.PHONY : device.s

# target to generate assembly for a file
device.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/device.cpp.s
.PHONY : device.cpp.s

gui.o: gui.cpp.o
.PHONY : gui.o

# target to build an object file
gui.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/gui.cpp.o
.PHONY : gui.cpp.o

gui.i: gui.cpp.i
.PHONY : gui.i

# target to preprocess a source file
gui.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/gui.cpp.i
.PHONY : gui.cpp.i

gui.s: gui.cpp.s
.PHONY : gui.s

# target to generate assembly for a file
gui.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/gui.cpp.s
.PHONY : gui.cpp.s

hid_libusb.o: hid_libusb.c.o
.PHONY : hid_libusb.o

# target to build an object file
hid_libusb.c.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hid_libusb.c.o
.PHONY : hid_libusb.c.o

hid_libusb.i: hid_libusb.c.i
.PHONY : hid_libusb.i

# target to preprocess a source file
hid_libusb.c.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hid_libusb.c.i
.PHONY : hid_libusb.c.i

hid_libusb.s: hid_libusb.c.s
.PHONY : hid_libusb.s

# target to generate assembly for a file
hid_libusb.c.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hid_libusb.c.s
.PHONY : hid_libusb.c.s

hotpdialog.o: hotpdialog.cpp.o
.PHONY : hotpdialog.o

# target to build an object file
hotpdialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hotpdialog.cpp.o
.PHONY : hotpdialog.cpp.o

hotpdialog.i: hotpdialog.cpp.i
.PHONY : hotpdialog.i

# target to preprocess a source file
hotpdialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hotpdialog.cpp.i
.PHONY : hotpdialog.cpp.i

hotpdialog.s: hotpdialog.cpp.s
.PHONY : hotpdialog.s

# target to generate assembly for a file
hotpdialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hotpdialog.cpp.s
.PHONY : hotpdialog.cpp.s

hotpslot.o: hotpslot.cpp.o
.PHONY : hotpslot.o

# target to build an object file
hotpslot.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hotpslot.cpp.o
.PHONY : hotpslot.cpp.o

hotpslot.i: hotpslot.cpp.i
.PHONY : hotpslot.i

# target to preprocess a source file
hotpslot.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hotpslot.cpp.i
.PHONY : hotpslot.cpp.i

hotpslot.s: hotpslot.cpp.s
.PHONY : hotpslot.s

# target to generate assembly for a file
hotpslot.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/hotpslot.cpp.s
.PHONY : hotpslot.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

moc_aboutdialog.o: moc_aboutdialog.cpp.o
.PHONY : moc_aboutdialog.o

# target to build an object file
moc_aboutdialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_aboutdialog.cpp.o
.PHONY : moc_aboutdialog.cpp.o

moc_aboutdialog.i: moc_aboutdialog.cpp.i
.PHONY : moc_aboutdialog.i

# target to preprocess a source file
moc_aboutdialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_aboutdialog.cpp.i
.PHONY : moc_aboutdialog.cpp.i

moc_aboutdialog.s: moc_aboutdialog.cpp.s
.PHONY : moc_aboutdialog.s

# target to generate assembly for a file
moc_aboutdialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_aboutdialog.cpp.s
.PHONY : moc_aboutdialog.cpp.s

moc_base32.o: moc_base32.cpp.o
.PHONY : moc_base32.o

# target to build an object file
moc_base32.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_base32.cpp.o
.PHONY : moc_base32.cpp.o

moc_base32.i: moc_base32.cpp.i
.PHONY : moc_base32.i

# target to preprocess a source file
moc_base32.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_base32.cpp.i
.PHONY : moc_base32.cpp.i

moc_base32.s: moc_base32.cpp.s
.PHONY : moc_base32.s

# target to generate assembly for a file
moc_base32.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_base32.cpp.s
.PHONY : moc_base32.cpp.s

moc_command.o: moc_command.cpp.o
.PHONY : moc_command.o

# target to build an object file
moc_command.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_command.cpp.o
.PHONY : moc_command.cpp.o

moc_command.i: moc_command.cpp.i
.PHONY : moc_command.i

# target to preprocess a source file
moc_command.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_command.cpp.i
.PHONY : moc_command.cpp.i

moc_command.s: moc_command.cpp.s
.PHONY : moc_command.s

# target to generate assembly for a file
moc_command.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_command.cpp.s
.PHONY : moc_command.cpp.s

moc_crc32.o: moc_crc32.cpp.o
.PHONY : moc_crc32.o

# target to build an object file
moc_crc32.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_crc32.cpp.o
.PHONY : moc_crc32.cpp.o

moc_crc32.i: moc_crc32.cpp.i
.PHONY : moc_crc32.i

# target to preprocess a source file
moc_crc32.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_crc32.cpp.i
.PHONY : moc_crc32.cpp.i

moc_crc32.s: moc_crc32.cpp.s
.PHONY : moc_crc32.s

# target to generate assembly for a file
moc_crc32.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_crc32.cpp.s
.PHONY : moc_crc32.cpp.s

moc_device.o: moc_device.cpp.o
.PHONY : moc_device.o

# target to build an object file
moc_device.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_device.cpp.o
.PHONY : moc_device.cpp.o

moc_device.i: moc_device.cpp.i
.PHONY : moc_device.i

# target to preprocess a source file
moc_device.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_device.cpp.i
.PHONY : moc_device.cpp.i

moc_device.s: moc_device.cpp.s
.PHONY : moc_device.s

# target to generate assembly for a file
moc_device.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_device.cpp.s
.PHONY : moc_device.cpp.s

moc_gui.o: moc_gui.cpp.o
.PHONY : moc_gui.o

# target to build an object file
moc_gui.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_gui.cpp.o
.PHONY : moc_gui.cpp.o

moc_gui.i: moc_gui.cpp.i
.PHONY : moc_gui.i

# target to preprocess a source file
moc_gui.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_gui.cpp.i
.PHONY : moc_gui.cpp.i

moc_gui.s: moc_gui.cpp.s
.PHONY : moc_gui.s

# target to generate assembly for a file
moc_gui.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_gui.cpp.s
.PHONY : moc_gui.cpp.s

moc_hidapi.o: moc_hidapi.cpp.o
.PHONY : moc_hidapi.o

# target to build an object file
moc_hidapi.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hidapi.cpp.o
.PHONY : moc_hidapi.cpp.o

moc_hidapi.i: moc_hidapi.cpp.i
.PHONY : moc_hidapi.i

# target to preprocess a source file
moc_hidapi.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hidapi.cpp.i
.PHONY : moc_hidapi.cpp.i

moc_hidapi.s: moc_hidapi.cpp.s
.PHONY : moc_hidapi.s

# target to generate assembly for a file
moc_hidapi.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hidapi.cpp.s
.PHONY : moc_hidapi.cpp.s

moc_hotpdialog.o: moc_hotpdialog.cpp.o
.PHONY : moc_hotpdialog.o

# target to build an object file
moc_hotpdialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hotpdialog.cpp.o
.PHONY : moc_hotpdialog.cpp.o

moc_hotpdialog.i: moc_hotpdialog.cpp.i
.PHONY : moc_hotpdialog.i

# target to preprocess a source file
moc_hotpdialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hotpdialog.cpp.i
.PHONY : moc_hotpdialog.cpp.i

moc_hotpdialog.s: moc_hotpdialog.cpp.s
.PHONY : moc_hotpdialog.s

# target to generate assembly for a file
moc_hotpdialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hotpdialog.cpp.s
.PHONY : moc_hotpdialog.cpp.s

moc_hotpslot.o: moc_hotpslot.cpp.o
.PHONY : moc_hotpslot.o

# target to build an object file
moc_hotpslot.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hotpslot.cpp.o
.PHONY : moc_hotpslot.cpp.o

moc_hotpslot.i: moc_hotpslot.cpp.i
.PHONY : moc_hotpslot.i

# target to preprocess a source file
moc_hotpslot.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hotpslot.cpp.i
.PHONY : moc_hotpslot.cpp.i

moc_hotpslot.s: moc_hotpslot.cpp.s
.PHONY : moc_hotpslot.s

# target to generate assembly for a file
moc_hotpslot.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_hotpslot.cpp.s
.PHONY : moc_hotpslot.cpp.s

moc_inttypes.o: moc_inttypes.cpp.o
.PHONY : moc_inttypes.o

# target to build an object file
moc_inttypes.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_inttypes.cpp.o
.PHONY : moc_inttypes.cpp.o

moc_inttypes.i: moc_inttypes.cpp.i
.PHONY : moc_inttypes.i

# target to preprocess a source file
moc_inttypes.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_inttypes.cpp.i
.PHONY : moc_inttypes.cpp.i

moc_inttypes.s: moc_inttypes.cpp.s
.PHONY : moc_inttypes.s

# target to generate assembly for a file
moc_inttypes.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_inttypes.cpp.s
.PHONY : moc_inttypes.cpp.s

moc_mainwindow.o: moc_mainwindow.cpp.o
.PHONY : moc_mainwindow.o

# target to build an object file
moc_mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_mainwindow.cpp.o
.PHONY : moc_mainwindow.cpp.o

moc_mainwindow.i: moc_mainwindow.cpp.i
.PHONY : moc_mainwindow.i

# target to preprocess a source file
moc_mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_mainwindow.cpp.i
.PHONY : moc_mainwindow.cpp.i

moc_mainwindow.s: moc_mainwindow.cpp.s
.PHONY : moc_mainwindow.s

# target to generate assembly for a file
moc_mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_mainwindow.cpp.s
.PHONY : moc_mainwindow.cpp.s

moc_mcvs-wrapper.o: moc_mcvs-wrapper.cpp.o
.PHONY : moc_mcvs-wrapper.o

# target to build an object file
moc_mcvs-wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_mcvs-wrapper.cpp.o
.PHONY : moc_mcvs-wrapper.cpp.o

moc_mcvs-wrapper.i: moc_mcvs-wrapper.cpp.i
.PHONY : moc_mcvs-wrapper.i

# target to preprocess a source file
moc_mcvs-wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_mcvs-wrapper.cpp.i
.PHONY : moc_mcvs-wrapper.cpp.i

moc_mcvs-wrapper.s: moc_mcvs-wrapper.cpp.s
.PHONY : moc_mcvs-wrapper.s

# target to generate assembly for a file
moc_mcvs-wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_mcvs-wrapper.cpp.s
.PHONY : moc_mcvs-wrapper.cpp.s

moc_nitrokey-applet.o: moc_nitrokey-applet.cpp.o
.PHONY : moc_nitrokey-applet.o

# target to build an object file
moc_nitrokey-applet.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_nitrokey-applet.cpp.o
.PHONY : moc_nitrokey-applet.cpp.o

moc_nitrokey-applet.i: moc_nitrokey-applet.cpp.i
.PHONY : moc_nitrokey-applet.i

# target to preprocess a source file
moc_nitrokey-applet.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_nitrokey-applet.cpp.i
.PHONY : moc_nitrokey-applet.cpp.i

moc_nitrokey-applet.s: moc_nitrokey-applet.cpp.s
.PHONY : moc_nitrokey-applet.s

# target to generate assembly for a file
moc_nitrokey-applet.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_nitrokey-applet.cpp.s
.PHONY : moc_nitrokey-applet.cpp.s

moc_passworddialog.o: moc_passworddialog.cpp.o
.PHONY : moc_passworddialog.o

# target to build an object file
moc_passworddialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_passworddialog.cpp.o
.PHONY : moc_passworddialog.cpp.o

moc_passworddialog.i: moc_passworddialog.cpp.i
.PHONY : moc_passworddialog.i

# target to preprocess a source file
moc_passworddialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_passworddialog.cpp.i
.PHONY : moc_passworddialog.cpp.i

moc_passworddialog.s: moc_passworddialog.cpp.s
.PHONY : moc_passworddialog.s

# target to generate assembly for a file
moc_passworddialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_passworddialog.cpp.s
.PHONY : moc_passworddialog.cpp.s

moc_passwordsafedialog.o: moc_passwordsafedialog.cpp.o
.PHONY : moc_passwordsafedialog.o

# target to build an object file
moc_passwordsafedialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_passwordsafedialog.cpp.o
.PHONY : moc_passwordsafedialog.cpp.o

moc_passwordsafedialog.i: moc_passwordsafedialog.cpp.i
.PHONY : moc_passwordsafedialog.i

# target to preprocess a source file
moc_passwordsafedialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_passwordsafedialog.cpp.i
.PHONY : moc_passwordsafedialog.cpp.i

moc_passwordsafedialog.s: moc_passwordsafedialog.cpp.s
.PHONY : moc_passwordsafedialog.s

# target to generate assembly for a file
moc_passwordsafedialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_passwordsafedialog.cpp.s
.PHONY : moc_passwordsafedialog.cpp.s

moc_pindialog.o: moc_pindialog.cpp.o
.PHONY : moc_pindialog.o

# target to build an object file
moc_pindialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_pindialog.cpp.o
.PHONY : moc_pindialog.cpp.o

moc_pindialog.i: moc_pindialog.cpp.i
.PHONY : moc_pindialog.i

# target to preprocess a source file
moc_pindialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_pindialog.cpp.i
.PHONY : moc_pindialog.cpp.i

moc_pindialog.s: moc_pindialog.cpp.s
.PHONY : moc_pindialog.s

# target to generate assembly for a file
moc_pindialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_pindialog.cpp.s
.PHONY : moc_pindialog.cpp.s

moc_response.o: moc_response.cpp.o
.PHONY : moc_response.o

# target to build an object file
moc_response.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_response.cpp.o
.PHONY : moc_response.cpp.o

moc_response.i: moc_response.cpp.i
.PHONY : moc_response.i

# target to preprocess a source file
moc_response.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_response.cpp.i
.PHONY : moc_response.cpp.i

moc_response.s: moc_response.cpp.s
.PHONY : moc_response.s

# target to generate assembly for a file
moc_response.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_response.cpp.s
.PHONY : moc_response.cpp.s

moc_securitydialog.o: moc_securitydialog.cpp.o
.PHONY : moc_securitydialog.o

# target to build an object file
moc_securitydialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_securitydialog.cpp.o
.PHONY : moc_securitydialog.cpp.o

moc_securitydialog.i: moc_securitydialog.cpp.i
.PHONY : moc_securitydialog.i

# target to preprocess a source file
moc_securitydialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_securitydialog.cpp.i
.PHONY : moc_securitydialog.cpp.i

moc_securitydialog.s: moc_securitydialog.cpp.s
.PHONY : moc_securitydialog.s

# target to generate assembly for a file
moc_securitydialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_securitydialog.cpp.s
.PHONY : moc_securitydialog.cpp.s

moc_sleep.o: moc_sleep.cpp.o
.PHONY : moc_sleep.o

# target to build an object file
moc_sleep.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_sleep.cpp.o
.PHONY : moc_sleep.cpp.o

moc_sleep.i: moc_sleep.cpp.i
.PHONY : moc_sleep.i

# target to preprocess a source file
moc_sleep.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_sleep.cpp.i
.PHONY : moc_sleep.cpp.i

moc_sleep.s: moc_sleep.cpp.s
.PHONY : moc_sleep.s

# target to generate assembly for a file
moc_sleep.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_sleep.cpp.s
.PHONY : moc_sleep.cpp.s

moc_splash.o: moc_splash.cpp.o
.PHONY : moc_splash.o

# target to build an object file
moc_splash.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_splash.cpp.o
.PHONY : moc_splash.cpp.o

moc_splash.i: moc_splash.cpp.i
.PHONY : moc_splash.i

# target to preprocess a source file
moc_splash.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_splash.cpp.i
.PHONY : moc_splash.cpp.i

moc_splash.s: moc_splash.cpp.s
.PHONY : moc_splash.s

# target to generate assembly for a file
moc_splash.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_splash.cpp.s
.PHONY : moc_splash.cpp.s

moc_stick20changepassworddialog.o: moc_stick20changepassworddialog.cpp.o
.PHONY : moc_stick20changepassworddialog.o

# target to build an object file
moc_stick20changepassworddialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20changepassworddialog.cpp.o
.PHONY : moc_stick20changepassworddialog.cpp.o

moc_stick20changepassworddialog.i: moc_stick20changepassworddialog.cpp.i
.PHONY : moc_stick20changepassworddialog.i

# target to preprocess a source file
moc_stick20changepassworddialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20changepassworddialog.cpp.i
.PHONY : moc_stick20changepassworddialog.cpp.i

moc_stick20changepassworddialog.s: moc_stick20changepassworddialog.cpp.s
.PHONY : moc_stick20changepassworddialog.s

# target to generate assembly for a file
moc_stick20changepassworddialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20changepassworddialog.cpp.s
.PHONY : moc_stick20changepassworddialog.cpp.s

moc_stick20debugdialog.o: moc_stick20debugdialog.cpp.o
.PHONY : moc_stick20debugdialog.o

# target to build an object file
moc_stick20debugdialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20debugdialog.cpp.o
.PHONY : moc_stick20debugdialog.cpp.o

moc_stick20debugdialog.i: moc_stick20debugdialog.cpp.i
.PHONY : moc_stick20debugdialog.i

# target to preprocess a source file
moc_stick20debugdialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20debugdialog.cpp.i
.PHONY : moc_stick20debugdialog.cpp.i

moc_stick20debugdialog.s: moc_stick20debugdialog.cpp.s
.PHONY : moc_stick20debugdialog.s

# target to generate assembly for a file
moc_stick20debugdialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20debugdialog.cpp.s
.PHONY : moc_stick20debugdialog.cpp.s

moc_stick20dialog.o: moc_stick20dialog.cpp.o
.PHONY : moc_stick20dialog.o

# target to build an object file
moc_stick20dialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20dialog.cpp.o
.PHONY : moc_stick20dialog.cpp.o

moc_stick20dialog.i: moc_stick20dialog.cpp.i
.PHONY : moc_stick20dialog.i

# target to preprocess a source file
moc_stick20dialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20dialog.cpp.i
.PHONY : moc_stick20dialog.cpp.i

moc_stick20dialog.s: moc_stick20dialog.cpp.s
.PHONY : moc_stick20dialog.s

# target to generate assembly for a file
moc_stick20dialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20dialog.cpp.s
.PHONY : moc_stick20dialog.cpp.s

moc_stick20hid.o: moc_stick20hid.cpp.o
.PHONY : moc_stick20hid.o

# target to build an object file
moc_stick20hid.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20hid.cpp.o
.PHONY : moc_stick20hid.cpp.o

moc_stick20hid.i: moc_stick20hid.cpp.i
.PHONY : moc_stick20hid.i

# target to preprocess a source file
moc_stick20hid.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20hid.cpp.i
.PHONY : moc_stick20hid.cpp.i

moc_stick20hid.s: moc_stick20hid.cpp.s
.PHONY : moc_stick20hid.s

# target to generate assembly for a file
moc_stick20hid.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20hid.cpp.s
.PHONY : moc_stick20hid.cpp.s

moc_stick20hiddenvolumedialog.o: moc_stick20hiddenvolumedialog.cpp.o
.PHONY : moc_stick20hiddenvolumedialog.o

# target to build an object file
moc_stick20hiddenvolumedialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20hiddenvolumedialog.cpp.o
.PHONY : moc_stick20hiddenvolumedialog.cpp.o

moc_stick20hiddenvolumedialog.i: moc_stick20hiddenvolumedialog.cpp.i
.PHONY : moc_stick20hiddenvolumedialog.i

# target to preprocess a source file
moc_stick20hiddenvolumedialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20hiddenvolumedialog.cpp.i
.PHONY : moc_stick20hiddenvolumedialog.cpp.i

moc_stick20hiddenvolumedialog.s: moc_stick20hiddenvolumedialog.cpp.s
.PHONY : moc_stick20hiddenvolumedialog.s

# target to generate assembly for a file
moc_stick20hiddenvolumedialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20hiddenvolumedialog.cpp.s
.PHONY : moc_stick20hiddenvolumedialog.cpp.s

moc_stick20infodialog.o: moc_stick20infodialog.cpp.o
.PHONY : moc_stick20infodialog.o

# target to build an object file
moc_stick20infodialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20infodialog.cpp.o
.PHONY : moc_stick20infodialog.cpp.o

moc_stick20infodialog.i: moc_stick20infodialog.cpp.i
.PHONY : moc_stick20infodialog.i

# target to preprocess a source file
moc_stick20infodialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20infodialog.cpp.i
.PHONY : moc_stick20infodialog.cpp.i

moc_stick20infodialog.s: moc_stick20infodialog.cpp.s
.PHONY : moc_stick20infodialog.s

# target to generate assembly for a file
moc_stick20infodialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20infodialog.cpp.s
.PHONY : moc_stick20infodialog.cpp.s

moc_stick20lockfirmwaredialog.o: moc_stick20lockfirmwaredialog.cpp.o
.PHONY : moc_stick20lockfirmwaredialog.o

# target to build an object file
moc_stick20lockfirmwaredialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20lockfirmwaredialog.cpp.o
.PHONY : moc_stick20lockfirmwaredialog.cpp.o

moc_stick20lockfirmwaredialog.i: moc_stick20lockfirmwaredialog.cpp.i
.PHONY : moc_stick20lockfirmwaredialog.i

# target to preprocess a source file
moc_stick20lockfirmwaredialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20lockfirmwaredialog.cpp.i
.PHONY : moc_stick20lockfirmwaredialog.cpp.i

moc_stick20lockfirmwaredialog.s: moc_stick20lockfirmwaredialog.cpp.s
.PHONY : moc_stick20lockfirmwaredialog.s

# target to generate assembly for a file
moc_stick20lockfirmwaredialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20lockfirmwaredialog.cpp.s
.PHONY : moc_stick20lockfirmwaredialog.cpp.s

moc_stick20matrixpassworddialog.o: moc_stick20matrixpassworddialog.cpp.o
.PHONY : moc_stick20matrixpassworddialog.o

# target to build an object file
moc_stick20matrixpassworddialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20matrixpassworddialog.cpp.o
.PHONY : moc_stick20matrixpassworddialog.cpp.o

moc_stick20matrixpassworddialog.i: moc_stick20matrixpassworddialog.cpp.i
.PHONY : moc_stick20matrixpassworddialog.i

# target to preprocess a source file
moc_stick20matrixpassworddialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20matrixpassworddialog.cpp.i
.PHONY : moc_stick20matrixpassworddialog.cpp.i

moc_stick20matrixpassworddialog.s: moc_stick20matrixpassworddialog.cpp.s
.PHONY : moc_stick20matrixpassworddialog.s

# target to generate assembly for a file
moc_stick20matrixpassworddialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20matrixpassworddialog.cpp.s
.PHONY : moc_stick20matrixpassworddialog.cpp.s

moc_stick20responsedialog.o: moc_stick20responsedialog.cpp.o
.PHONY : moc_stick20responsedialog.o

# target to build an object file
moc_stick20responsedialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20responsedialog.cpp.o
.PHONY : moc_stick20responsedialog.cpp.o

moc_stick20responsedialog.i: moc_stick20responsedialog.cpp.i
.PHONY : moc_stick20responsedialog.i

# target to preprocess a source file
moc_stick20responsedialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20responsedialog.cpp.i
.PHONY : moc_stick20responsedialog.cpp.i

moc_stick20responsedialog.s: moc_stick20responsedialog.cpp.s
.PHONY : moc_stick20responsedialog.s

# target to generate assembly for a file
moc_stick20responsedialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20responsedialog.cpp.s
.PHONY : moc_stick20responsedialog.cpp.s

moc_stick20setup.o: moc_stick20setup.cpp.o
.PHONY : moc_stick20setup.o

# target to build an object file
moc_stick20setup.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20setup.cpp.o
.PHONY : moc_stick20setup.cpp.o

moc_stick20setup.i: moc_stick20setup.cpp.i
.PHONY : moc_stick20setup.i

# target to preprocess a source file
moc_stick20setup.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20setup.cpp.i
.PHONY : moc_stick20setup.cpp.i

moc_stick20setup.s: moc_stick20setup.cpp.s
.PHONY : moc_stick20setup.s

# target to generate assembly for a file
moc_stick20setup.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20setup.cpp.s
.PHONY : moc_stick20setup.cpp.s

moc_stick20updatedialog.o: moc_stick20updatedialog.cpp.o
.PHONY : moc_stick20updatedialog.o

# target to build an object file
moc_stick20updatedialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20updatedialog.cpp.o
.PHONY : moc_stick20updatedialog.cpp.o

moc_stick20updatedialog.i: moc_stick20updatedialog.cpp.i
.PHONY : moc_stick20updatedialog.i

# target to preprocess a source file
moc_stick20updatedialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20updatedialog.cpp.i
.PHONY : moc_stick20updatedialog.cpp.i

moc_stick20updatedialog.s: moc_stick20updatedialog.cpp.s
.PHONY : moc_stick20updatedialog.s

# target to generate assembly for a file
moc_stick20updatedialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20updatedialog.cpp.s
.PHONY : moc_stick20updatedialog.cpp.s

moc_stick20window.o: moc_stick20window.cpp.o
.PHONY : moc_stick20window.o

# target to build an object file
moc_stick20window.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20window.cpp.o
.PHONY : moc_stick20window.cpp.o

moc_stick20window.i: moc_stick20window.cpp.i
.PHONY : moc_stick20window.i

# target to preprocess a source file
moc_stick20window.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20window.cpp.i
.PHONY : moc_stick20window.cpp.i

moc_stick20window.s: moc_stick20window.cpp.s
.PHONY : moc_stick20window.s

# target to generate assembly for a file
moc_stick20window.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_stick20window.cpp.s
.PHONY : moc_stick20window.cpp.s

moc_totpslot.o: moc_totpslot.cpp.o
.PHONY : moc_totpslot.o

# target to build an object file
moc_totpslot.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_totpslot.cpp.o
.PHONY : moc_totpslot.cpp.o

moc_totpslot.i: moc_totpslot.cpp.i
.PHONY : moc_totpslot.i

# target to preprocess a source file
moc_totpslot.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_totpslot.cpp.i
.PHONY : moc_totpslot.cpp.i

moc_totpslot.s: moc_totpslot.cpp.s
.PHONY : moc_totpslot.s

# target to generate assembly for a file
moc_totpslot.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/moc_totpslot.cpp.s
.PHONY : moc_totpslot.cpp.s

nitrokey-applet.o: nitrokey-applet.cpp.o
.PHONY : nitrokey-applet.o

# target to build an object file
nitrokey-applet.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/nitrokey-applet.cpp.o
.PHONY : nitrokey-applet.cpp.o

nitrokey-applet.i: nitrokey-applet.cpp.i
.PHONY : nitrokey-applet.i

# target to preprocess a source file
nitrokey-applet.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/nitrokey-applet.cpp.i
.PHONY : nitrokey-applet.cpp.i

nitrokey-applet.s: nitrokey-applet.cpp.s
.PHONY : nitrokey-applet.s

# target to generate assembly for a file
nitrokey-applet.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/nitrokey-applet.cpp.s
.PHONY : nitrokey-applet.cpp.s

passworddialog.o: passworddialog.cpp.o
.PHONY : passworddialog.o

# target to build an object file
passworddialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/passworddialog.cpp.o
.PHONY : passworddialog.cpp.o

passworddialog.i: passworddialog.cpp.i
.PHONY : passworddialog.i

# target to preprocess a source file
passworddialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/passworddialog.cpp.i
.PHONY : passworddialog.cpp.i

passworddialog.s: passworddialog.cpp.s
.PHONY : passworddialog.s

# target to generate assembly for a file
passworddialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/passworddialog.cpp.s
.PHONY : passworddialog.cpp.s

passwordsafedialog.o: passwordsafedialog.cpp.o
.PHONY : passwordsafedialog.o

# target to build an object file
passwordsafedialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/passwordsafedialog.cpp.o
.PHONY : passwordsafedialog.cpp.o

passwordsafedialog.i: passwordsafedialog.cpp.i
.PHONY : passwordsafedialog.i

# target to preprocess a source file
passwordsafedialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/passwordsafedialog.cpp.i
.PHONY : passwordsafedialog.cpp.i

passwordsafedialog.s: passwordsafedialog.cpp.s
.PHONY : passwordsafedialog.s

# target to generate assembly for a file
passwordsafedialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/passwordsafedialog.cpp.s
.PHONY : passwordsafedialog.cpp.s

pindialog.o: pindialog.cpp.o
.PHONY : pindialog.o

# target to build an object file
pindialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/pindialog.cpp.o
.PHONY : pindialog.cpp.o

pindialog.i: pindialog.cpp.i
.PHONY : pindialog.i

# target to preprocess a source file
pindialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/pindialog.cpp.i
.PHONY : pindialog.cpp.i

pindialog.s: pindialog.cpp.s
.PHONY : pindialog.s

# target to generate assembly for a file
pindialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/pindialog.cpp.s
.PHONY : pindialog.cpp.s

qrc_resources.o: qrc_resources.cpp.o
.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/qrc_resources.cpp.o
.PHONY : qrc_resources.cpp.o

qrc_resources.i: qrc_resources.cpp.i
.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/qrc_resources.cpp.i
.PHONY : qrc_resources.cpp.i

qrc_resources.s: qrc_resources.cpp.s
.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/qrc_resources.cpp.s
.PHONY : qrc_resources.cpp.s

response.o: response.cpp.o
.PHONY : response.o

# target to build an object file
response.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/response.cpp.o
.PHONY : response.cpp.o

response.i: response.cpp.i
.PHONY : response.i

# target to preprocess a source file
response.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/response.cpp.i
.PHONY : response.cpp.i

response.s: response.cpp.s
.PHONY : response.s

# target to generate assembly for a file
response.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/response.cpp.s
.PHONY : response.cpp.s

securitydialog.o: securitydialog.cpp.o
.PHONY : securitydialog.o

# target to build an object file
securitydialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/securitydialog.cpp.o
.PHONY : securitydialog.cpp.o

securitydialog.i: securitydialog.cpp.i
.PHONY : securitydialog.i

# target to preprocess a source file
securitydialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/securitydialog.cpp.i
.PHONY : securitydialog.cpp.i

securitydialog.s: securitydialog.cpp.s
.PHONY : securitydialog.s

# target to generate assembly for a file
securitydialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/securitydialog.cpp.s
.PHONY : securitydialog.cpp.s

splash.o: splash.cpp.o
.PHONY : splash.o

# target to build an object file
splash.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/splash.cpp.o
.PHONY : splash.cpp.o

splash.i: splash.cpp.i
.PHONY : splash.i

# target to preprocess a source file
splash.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/splash.cpp.i
.PHONY : splash.cpp.i

splash.s: splash.cpp.s
.PHONY : splash.s

# target to generate assembly for a file
splash.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/splash.cpp.s
.PHONY : splash.cpp.s

stick20changepassworddialog.o: stick20changepassworddialog.cpp.o
.PHONY : stick20changepassworddialog.o

# target to build an object file
stick20changepassworddialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20changepassworddialog.cpp.o
.PHONY : stick20changepassworddialog.cpp.o

stick20changepassworddialog.i: stick20changepassworddialog.cpp.i
.PHONY : stick20changepassworddialog.i

# target to preprocess a source file
stick20changepassworddialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20changepassworddialog.cpp.i
.PHONY : stick20changepassworddialog.cpp.i

stick20changepassworddialog.s: stick20changepassworddialog.cpp.s
.PHONY : stick20changepassworddialog.s

# target to generate assembly for a file
stick20changepassworddialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20changepassworddialog.cpp.s
.PHONY : stick20changepassworddialog.cpp.s

stick20debugdialog.o: stick20debugdialog.cpp.o
.PHONY : stick20debugdialog.o

# target to build an object file
stick20debugdialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20debugdialog.cpp.o
.PHONY : stick20debugdialog.cpp.o

stick20debugdialog.i: stick20debugdialog.cpp.i
.PHONY : stick20debugdialog.i

# target to preprocess a source file
stick20debugdialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20debugdialog.cpp.i
.PHONY : stick20debugdialog.cpp.i

stick20debugdialog.s: stick20debugdialog.cpp.s
.PHONY : stick20debugdialog.s

# target to generate assembly for a file
stick20debugdialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20debugdialog.cpp.s
.PHONY : stick20debugdialog.cpp.s

stick20dialog.o: stick20dialog.cpp.o
.PHONY : stick20dialog.o

# target to build an object file
stick20dialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20dialog.cpp.o
.PHONY : stick20dialog.cpp.o

stick20dialog.i: stick20dialog.cpp.i
.PHONY : stick20dialog.i

# target to preprocess a source file
stick20dialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20dialog.cpp.i
.PHONY : stick20dialog.cpp.i

stick20dialog.s: stick20dialog.cpp.s
.PHONY : stick20dialog.s

# target to generate assembly for a file
stick20dialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20dialog.cpp.s
.PHONY : stick20dialog.cpp.s

stick20hid.o: stick20hid.c.o
.PHONY : stick20hid.o

# target to build an object file
stick20hid.c.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20hid.c.o
.PHONY : stick20hid.c.o

stick20hid.i: stick20hid.c.i
.PHONY : stick20hid.i

# target to preprocess a source file
stick20hid.c.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20hid.c.i
.PHONY : stick20hid.c.i

stick20hid.s: stick20hid.c.s
.PHONY : stick20hid.s

# target to generate assembly for a file
stick20hid.c.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20hid.c.s
.PHONY : stick20hid.c.s

stick20hiddenvolumedialog.o: stick20hiddenvolumedialog.cpp.o
.PHONY : stick20hiddenvolumedialog.o

# target to build an object file
stick20hiddenvolumedialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20hiddenvolumedialog.cpp.o
.PHONY : stick20hiddenvolumedialog.cpp.o

stick20hiddenvolumedialog.i: stick20hiddenvolumedialog.cpp.i
.PHONY : stick20hiddenvolumedialog.i

# target to preprocess a source file
stick20hiddenvolumedialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20hiddenvolumedialog.cpp.i
.PHONY : stick20hiddenvolumedialog.cpp.i

stick20hiddenvolumedialog.s: stick20hiddenvolumedialog.cpp.s
.PHONY : stick20hiddenvolumedialog.s

# target to generate assembly for a file
stick20hiddenvolumedialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20hiddenvolumedialog.cpp.s
.PHONY : stick20hiddenvolumedialog.cpp.s

stick20infodialog.o: stick20infodialog.cpp.o
.PHONY : stick20infodialog.o

# target to build an object file
stick20infodialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20infodialog.cpp.o
.PHONY : stick20infodialog.cpp.o

stick20infodialog.i: stick20infodialog.cpp.i
.PHONY : stick20infodialog.i

# target to preprocess a source file
stick20infodialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20infodialog.cpp.i
.PHONY : stick20infodialog.cpp.i

stick20infodialog.s: stick20infodialog.cpp.s
.PHONY : stick20infodialog.s

# target to generate assembly for a file
stick20infodialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20infodialog.cpp.s
.PHONY : stick20infodialog.cpp.s

stick20lockfirmwaredialog.o: stick20lockfirmwaredialog.cpp.o
.PHONY : stick20lockfirmwaredialog.o

# target to build an object file
stick20lockfirmwaredialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20lockfirmwaredialog.cpp.o
.PHONY : stick20lockfirmwaredialog.cpp.o

stick20lockfirmwaredialog.i: stick20lockfirmwaredialog.cpp.i
.PHONY : stick20lockfirmwaredialog.i

# target to preprocess a source file
stick20lockfirmwaredialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20lockfirmwaredialog.cpp.i
.PHONY : stick20lockfirmwaredialog.cpp.i

stick20lockfirmwaredialog.s: stick20lockfirmwaredialog.cpp.s
.PHONY : stick20lockfirmwaredialog.s

# target to generate assembly for a file
stick20lockfirmwaredialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20lockfirmwaredialog.cpp.s
.PHONY : stick20lockfirmwaredialog.cpp.s

stick20matrixpassworddialog.o: stick20matrixpassworddialog.cpp.o
.PHONY : stick20matrixpassworddialog.o

# target to build an object file
stick20matrixpassworddialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20matrixpassworddialog.cpp.o
.PHONY : stick20matrixpassworddialog.cpp.o

stick20matrixpassworddialog.i: stick20matrixpassworddialog.cpp.i
.PHONY : stick20matrixpassworddialog.i

# target to preprocess a source file
stick20matrixpassworddialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20matrixpassworddialog.cpp.i
.PHONY : stick20matrixpassworddialog.cpp.i

stick20matrixpassworddialog.s: stick20matrixpassworddialog.cpp.s
.PHONY : stick20matrixpassworddialog.s

# target to generate assembly for a file
stick20matrixpassworddialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20matrixpassworddialog.cpp.s
.PHONY : stick20matrixpassworddialog.cpp.s

stick20responsedialog.o: stick20responsedialog.cpp.o
.PHONY : stick20responsedialog.o

# target to build an object file
stick20responsedialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20responsedialog.cpp.o
.PHONY : stick20responsedialog.cpp.o

stick20responsedialog.i: stick20responsedialog.cpp.i
.PHONY : stick20responsedialog.i

# target to preprocess a source file
stick20responsedialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20responsedialog.cpp.i
.PHONY : stick20responsedialog.cpp.i

stick20responsedialog.s: stick20responsedialog.cpp.s
.PHONY : stick20responsedialog.s

# target to generate assembly for a file
stick20responsedialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20responsedialog.cpp.s
.PHONY : stick20responsedialog.cpp.s

stick20setup.o: stick20setup.cpp.o
.PHONY : stick20setup.o

# target to build an object file
stick20setup.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20setup.cpp.o
.PHONY : stick20setup.cpp.o

stick20setup.i: stick20setup.cpp.i
.PHONY : stick20setup.i

# target to preprocess a source file
stick20setup.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20setup.cpp.i
.PHONY : stick20setup.cpp.i

stick20setup.s: stick20setup.cpp.s
.PHONY : stick20setup.s

# target to generate assembly for a file
stick20setup.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20setup.cpp.s
.PHONY : stick20setup.cpp.s

stick20updatedialog.o: stick20updatedialog.cpp.o
.PHONY : stick20updatedialog.o

# target to build an object file
stick20updatedialog.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20updatedialog.cpp.o
.PHONY : stick20updatedialog.cpp.o

stick20updatedialog.i: stick20updatedialog.cpp.i
.PHONY : stick20updatedialog.i

# target to preprocess a source file
stick20updatedialog.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20updatedialog.cpp.i
.PHONY : stick20updatedialog.cpp.i

stick20updatedialog.s: stick20updatedialog.cpp.s
.PHONY : stick20updatedialog.s

# target to generate assembly for a file
stick20updatedialog.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20updatedialog.cpp.s
.PHONY : stick20updatedialog.cpp.s

stick20window.o: stick20window.cpp.o
.PHONY : stick20window.o

# target to build an object file
stick20window.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20window.cpp.o
.PHONY : stick20window.cpp.o

stick20window.i: stick20window.cpp.i
.PHONY : stick20window.i

# target to preprocess a source file
stick20window.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20window.cpp.i
.PHONY : stick20window.cpp.i

stick20window.s: stick20window.cpp.s
.PHONY : stick20window.s

# target to generate assembly for a file
stick20window.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/stick20window.cpp.s
.PHONY : stick20window.cpp.s

totpslot.o: totpslot.cpp.o
.PHONY : totpslot.o

# target to build an object file
totpslot.cpp.o:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/totpslot.cpp.o
.PHONY : totpslot.cpp.o

totpslot.i: totpslot.cpp.i
.PHONY : totpslot.i

# target to preprocess a source file
totpslot.cpp.i:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/totpslot.cpp.i
.PHONY : totpslot.cpp.i

totpslot.s: totpslot.cpp.s
.PHONY : totpslot.s

# target to generate assembly for a file
totpslot.cpp.s:
	$(MAKE) -f CMakeFiles/nitrokey-app.dir/build.make CMakeFiles/nitrokey-app.dir/totpslot.cpp.s
.PHONY : totpslot.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... nitrokey-app"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... aboutdialog.o"
	@echo "... aboutdialog.i"
	@echo "... aboutdialog.s"
	@echo "... base32.o"
	@echo "... base32.i"
	@echo "... base32.s"
	@echo "... command.o"
	@echo "... command.i"
	@echo "... command.s"
	@echo "... crc32.o"
	@echo "... crc32.i"
	@echo "... crc32.s"
	@echo "... device.o"
	@echo "... device.i"
	@echo "... device.s"
	@echo "... gui.o"
	@echo "... gui.i"
	@echo "... gui.s"
	@echo "... hid_libusb.o"
	@echo "... hid_libusb.i"
	@echo "... hid_libusb.s"
	@echo "... hotpdialog.o"
	@echo "... hotpdialog.i"
	@echo "... hotpdialog.s"
	@echo "... hotpslot.o"
	@echo "... hotpslot.i"
	@echo "... hotpslot.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... moc_aboutdialog.o"
	@echo "... moc_aboutdialog.i"
	@echo "... moc_aboutdialog.s"
	@echo "... moc_base32.o"
	@echo "... moc_base32.i"
	@echo "... moc_base32.s"
	@echo "... moc_command.o"
	@echo "... moc_command.i"
	@echo "... moc_command.s"
	@echo "... moc_crc32.o"
	@echo "... moc_crc32.i"
	@echo "... moc_crc32.s"
	@echo "... moc_device.o"
	@echo "... moc_device.i"
	@echo "... moc_device.s"
	@echo "... moc_gui.o"
	@echo "... moc_gui.i"
	@echo "... moc_gui.s"
	@echo "... moc_hidapi.o"
	@echo "... moc_hidapi.i"
	@echo "... moc_hidapi.s"
	@echo "... moc_hotpdialog.o"
	@echo "... moc_hotpdialog.i"
	@echo "... moc_hotpdialog.s"
	@echo "... moc_hotpslot.o"
	@echo "... moc_hotpslot.i"
	@echo "... moc_hotpslot.s"
	@echo "... moc_inttypes.o"
	@echo "... moc_inttypes.i"
	@echo "... moc_inttypes.s"
	@echo "... moc_mainwindow.o"
	@echo "... moc_mainwindow.i"
	@echo "... moc_mainwindow.s"
	@echo "... moc_mcvs-wrapper.o"
	@echo "... moc_mcvs-wrapper.i"
	@echo "... moc_mcvs-wrapper.s"
	@echo "... moc_nitrokey-applet.o"
	@echo "... moc_nitrokey-applet.i"
	@echo "... moc_nitrokey-applet.s"
	@echo "... moc_passworddialog.o"
	@echo "... moc_passworddialog.i"
	@echo "... moc_passworddialog.s"
	@echo "... moc_passwordsafedialog.o"
	@echo "... moc_passwordsafedialog.i"
	@echo "... moc_passwordsafedialog.s"
	@echo "... moc_pindialog.o"
	@echo "... moc_pindialog.i"
	@echo "... moc_pindialog.s"
	@echo "... moc_response.o"
	@echo "... moc_response.i"
	@echo "... moc_response.s"
	@echo "... moc_securitydialog.o"
	@echo "... moc_securitydialog.i"
	@echo "... moc_securitydialog.s"
	@echo "... moc_sleep.o"
	@echo "... moc_sleep.i"
	@echo "... moc_sleep.s"
	@echo "... moc_splash.o"
	@echo "... moc_splash.i"
	@echo "... moc_splash.s"
	@echo "... moc_stick20changepassworddialog.o"
	@echo "... moc_stick20changepassworddialog.i"
	@echo "... moc_stick20changepassworddialog.s"
	@echo "... moc_stick20debugdialog.o"
	@echo "... moc_stick20debugdialog.i"
	@echo "... moc_stick20debugdialog.s"
	@echo "... moc_stick20dialog.o"
	@echo "... moc_stick20dialog.i"
	@echo "... moc_stick20dialog.s"
	@echo "... moc_stick20hid.o"
	@echo "... moc_stick20hid.i"
	@echo "... moc_stick20hid.s"
	@echo "... moc_stick20hiddenvolumedialog.o"
	@echo "... moc_stick20hiddenvolumedialog.i"
	@echo "... moc_stick20hiddenvolumedialog.s"
	@echo "... moc_stick20infodialog.o"
	@echo "... moc_stick20infodialog.i"
	@echo "... moc_stick20infodialog.s"
	@echo "... moc_stick20lockfirmwaredialog.o"
	@echo "... moc_stick20lockfirmwaredialog.i"
	@echo "... moc_stick20lockfirmwaredialog.s"
	@echo "... moc_stick20matrixpassworddialog.o"
	@echo "... moc_stick20matrixpassworddialog.i"
	@echo "... moc_stick20matrixpassworddialog.s"
	@echo "... moc_stick20responsedialog.o"
	@echo "... moc_stick20responsedialog.i"
	@echo "... moc_stick20responsedialog.s"
	@echo "... moc_stick20setup.o"
	@echo "... moc_stick20setup.i"
	@echo "... moc_stick20setup.s"
	@echo "... moc_stick20updatedialog.o"
	@echo "... moc_stick20updatedialog.i"
	@echo "... moc_stick20updatedialog.s"
	@echo "... moc_stick20window.o"
	@echo "... moc_stick20window.i"
	@echo "... moc_stick20window.s"
	@echo "... moc_totpslot.o"
	@echo "... moc_totpslot.i"
	@echo "... moc_totpslot.s"
	@echo "... nitrokey-applet.o"
	@echo "... nitrokey-applet.i"
	@echo "... nitrokey-applet.s"
	@echo "... passworddialog.o"
	@echo "... passworddialog.i"
	@echo "... passworddialog.s"
	@echo "... passwordsafedialog.o"
	@echo "... passwordsafedialog.i"
	@echo "... passwordsafedialog.s"
	@echo "... pindialog.o"
	@echo "... pindialog.i"
	@echo "... pindialog.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
	@echo "... response.o"
	@echo "... response.i"
	@echo "... response.s"
	@echo "... securitydialog.o"
	@echo "... securitydialog.i"
	@echo "... securitydialog.s"
	@echo "... splash.o"
	@echo "... splash.i"
	@echo "... splash.s"
	@echo "... stick20changepassworddialog.o"
	@echo "... stick20changepassworddialog.i"
	@echo "... stick20changepassworddialog.s"
	@echo "... stick20debugdialog.o"
	@echo "... stick20debugdialog.i"
	@echo "... stick20debugdialog.s"
	@echo "... stick20dialog.o"
	@echo "... stick20dialog.i"
	@echo "... stick20dialog.s"
	@echo "... stick20hid.o"
	@echo "... stick20hid.i"
	@echo "... stick20hid.s"
	@echo "... stick20hiddenvolumedialog.o"
	@echo "... stick20hiddenvolumedialog.i"
	@echo "... stick20hiddenvolumedialog.s"
	@echo "... stick20infodialog.o"
	@echo "... stick20infodialog.i"
	@echo "... stick20infodialog.s"
	@echo "... stick20lockfirmwaredialog.o"
	@echo "... stick20lockfirmwaredialog.i"
	@echo "... stick20lockfirmwaredialog.s"
	@echo "... stick20matrixpassworddialog.o"
	@echo "... stick20matrixpassworddialog.i"
	@echo "... stick20matrixpassworddialog.s"
	@echo "... stick20responsedialog.o"
	@echo "... stick20responsedialog.i"
	@echo "... stick20responsedialog.s"
	@echo "... stick20setup.o"
	@echo "... stick20setup.i"
	@echo "... stick20setup.s"
	@echo "... stick20updatedialog.o"
	@echo "... stick20updatedialog.i"
	@echo "... stick20updatedialog.s"
	@echo "... stick20window.o"
	@echo "... stick20window.i"
	@echo "... stick20window.s"
	@echo "... totpslot.o"
	@echo "... totpslot.i"
	@echo "... totpslot.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

