# -*- rpm-spec -*-
BuildRoot:      /home/george/Projects/nitrokey/nitrokey-app/install/_CPack_Packages/Linux/RPM/nitrokey-app-1.0-Linux
Summary:        CryptoStickGUI built using CMake
Name:           nitrokey-app
Version:        1.0
Release:        1
License:        unknown
Group:          unknown
Vendor:         Humanity









Prefix: /usr

%define _rpmdir /home/george/Projects/nitrokey/nitrokey-app/install/_CPack_Packages/Linux/RPM
%define _rpmfilename nitrokey-app-1.0-Linux.rpm
%define _unpackaged_files_terminate_build 0
%define _topdir /home/george/Projects/nitrokey/nitrokey-app/install/_CPack_Packages/Linux/RPM




%description
DESCRIPTION
===========

This is an installer created using CPack (http://www.cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT "/home/george/Projects/nitrokey/nitrokey-app/install/_CPack_Packages/Linux/RPM/tmpBBroot"

#p build

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv "/home/george/Projects/nitrokey/nitrokey-app/install/_CPack_Packages/Linux/RPM/tmpBBroot" $RPM_BUILD_ROOT

%clean

%post


%postun


%pre


%preun


%files
%defattr(-,root,root,-)
"/usr/bin/nitrokey-app"
%dir "/usr/share/applications"
"/usr/share/applications/nitrokey-app.desktop"
%dir "/usr/share/pixmaps"
"/usr/share/pixmaps/nitrokey-app.png"
%dir "/usr/share/icons"
%dir "/usr/share/icons/hicolor"
%dir "/usr/share/icons/hicolor/24x24"
%dir "/usr/share/icons/hicolor/24x24/apps"
"/usr/share/icons/hicolor/24x24/apps/nitrokey-app.png"
%dir "/usr/share/icons/hicolor/scalable"
%dir "/usr/share/icons/hicolor/scalable/apps"
"/usr/share/icons/hicolor/scalable/apps/nitrokey-app.svg"
%dir "/usr/share/icons/hicolor/48x48"
%dir "/usr/share/icons/hicolor/48x48/apps"
"/usr/share/icons/hicolor/48x48/apps/nitrokey-app.png"
%dir "/usr/share/icons/hicolor/16x16"
%dir "/usr/share/icons/hicolor/16x16/apps"
"/usr/share/icons/hicolor/16x16/apps/nitrokey-app.png"
%dir "/usr/share/icons/hicolor/128x128"
%dir "/usr/share/icons/hicolor/128x128/apps"
"/usr/share/icons/hicolor/128x128/apps/nitrokey-app.png"
%dir "/usr/share/icons/hicolor/22x22"
%dir "/usr/share/icons/hicolor/22x22/apps"
"/usr/share/icons/hicolor/22x22/apps/nitrokey-app.png"
%dir "/usr/share/icons/hicolor/32x32"
%dir "/usr/share/icons/hicolor/32x32/apps"
"/usr/share/icons/hicolor/32x32/apps/nitrokey-app.png"




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 1.0-1
  Generated by CPack RPM (no Changelog file were provided)
